<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{


    protected $guarded = [];


    protected $casts = [
        'rv_content_lang' => 'array',
        'rv_content_network' => 'array',
        'rv_content' => 'array',
        'tmdb_lang' => 'array',
        'autosubstitles' => 'int',
        'wasabi_storage' => 'int',
        'aws_s3_storage' => 'int',
        'livetv' => 'int',
        'kids' => 'int',
        'livetv' => 'int',
        'ads_player' => 'int',
        'anime' => 'int',
        'ad_banner' => 'int',
        'ad_face_audience_interstitial' => 'int',
        'ad_face_audience_banner' => 'int',
        'featured_home_numbers' => 'int',
        'enable_custom_message' => 'int',
        'wach_ads_to_unlock' => 'int',
        'ad_interstitial' => 'int',
        'next_episode_timer' => 'int',
        'appodeal_show_interstitial' => 'int',
        'ad_unit_id_native_enable' => 'int',
        'appodeal_banner' => 'int',
        'appodeal_interstitial' => 'int',
        'server_dialog_selection' => 'int',
        'download_premuim_only' => 'int',
        'wach_ads_to_unlock_player' => 'int',
        'enable_custom_banner' => 'int',
        'mantenance_mode' => 'int',
        'allow_adm' => 'int',
        'enable_pinned' => 'int',
        'startapp_banner' => 'int',
        'startapp_interstitial' => 'int',
        'enable_vlc' => 'int',
        'resume_offline' => 'int',
        'unityads_banner' => 'int',
        'unityads_interstitial' => 'int',
        'streaming' => 'int',
        'enable_banner_bottom' => 'int',
        'ad_face_audience_native' => 'int',
        'enable_upcoming' => 'int',
        'enable_download' => 'int',
        'notification_separated' => 'int',
        'email_verify' => 'int',
        'force_login' => 'int',
        'favoriteonline' => 'int',
        'separate_download' => 'int',
        'vpn' => 'int',
        'notification_style' => 'int',
        'force_update' => 'int',
        'appnext_banner' => 'int',
        'appnext_interstitial' => 'int',
        'livetv_multi_servers' => 'int',
        'suggest_auth' => 'int',
        'networks' => 'int',
        'enable_webview' => 'int',
        'vungle_banner' => 'int',
        'vungle_interstitial' => 'int',
        'flag_secure' => 'int',
        'appnext_interstitial_show' => 'int',
        'vungle_interstitial_show' => 'int',
        'ironsource_banner' => 'int',
        'unity_show' => 'int',
        'root_detection' => 'int',
        'applovin_banner' => 'int',
        'applovin_interstitial' => 'int',
        'applovin_interstitial_show' => 'int',
        'ironsource_interstitial_show' => 'int',
        'force_password_access' => 'int',
        'force_inappupdate' => 'int',
        'enable_player_inter' => 'int',
        'enable_comments' => 'int',
        'applovin_native' => 'int',
        'enable_shadows' => 'int',
        'library_style' => 'int',
        'phone_verification' => 'int',
        'profile_selection' => 'int',
        'trustAllCerts' => 'int',
        'device_management' => 'int',
            'rv_content_lang' => 'array',
        'rv_content_network' => 'array',
        'rv_content' => 'array',
        'internallangs' => 'int',
        'searchhistory' => 'int',
        'forcewatchbyauth' => 'int',
        'safemode' => 'int',
        'enable_watchinyourlang' => 'int',
        'wortise_interstitial' => 'int',
        'wortise_banner' => 'int',
        'wortise_interstitial_show' => 'int',
        'wortise_banner_enable' => 'int',
        'enablelangsinservers' => 'int',
        'enablesociallogins' => 'int',
        'enabledynamicslider' => 'int',
        'slidertimer' => 'int',
        'device_management_limit' => 'int',
        'profile_selection_limit' => 'int',
        'enablelayoutchange' => 'int',
        'enable_shadows' => 'int',
        'enablecustomcontent' => 'int',
        'disablelogin' => 'int',
        'vidsrc' => 'int',
        'enable_collections' => 'int',
        'keep_local_copy' => 'int',
        'ftp_storage' => 'int',
        'ftp_port' => 'int',
        'ftp_pasv' => 'int',
        'ftp_ssl' => 'int',
        'webdav_storage' => 'int',
        'sftp_storage' => 'int',
        'sftp_port' => 'int',
    ];
   
}
